package com.artcom.y60.infrastructure;

public enum Errors {
	FILE_NOT_FOUND,
	MALFORMED_URI,
	UNSUPPORTED_ENCODING,
	SAX_ERROR,
	COMPONENT_NOT_FOUND,
	NETWORK_ERROR,
	JSON_ERROR,
	ILLEGAL_ARGUMENT,
}
