# valid suite settings: skip, normal, no-reinstall
suites:
    com.artcom.y60.dc.DeviceControllerHandlerTest:
        testmode : no-reinstall
    com.artcom.y60.dc.DeviceControllerServiceTest:
        testmode : no-reinstall
    com.artcom.y60.dc.DeviceControllerUnitTest:
        testmode : no-reinstall
    com.artcom.y60.dc.StatusWatcherTestCase:
        testmode : normal
